excluded:
- .git/*
- Pods

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- discouraged_optional_boolean
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- extension_access_modifier
- fatal_error_message
- file_name_no_space
- first_where
- identical_operands
- implicit_return
- last_where
- let_var_whitespace
- literal_expression_end_indentation
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- operator_usage_whitespace
- overridden_super_call
- pattern_matching_keywords
- prefer_zero_over_explicit_init
- redundant_type_annotation
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- toggle_bool
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- unused_import
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- yoda_condition

disabled_rules:
- attributes
- discarded_notification_center_observer
- force_cast
- force_try
- identifier_name
- implicit_return
- large_tuple
- multiline_arguments
- strict_fileprivate
- trailing_whitespace
- weak_delegate
